### ISSUE TITLE
Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error query options: 87 参数错误

### ISSUE THREAD

**Issue by managerstrange** [shadowsocks/shadowsocks-windows#2911] opened 2020-06-12 04:15 UTC
2020-06-12 11:42:46.4764|INFO|Shadowsocks.Program|controller stopped
2020-06-12 11:42:46.4764|INFO|Shadowsocks.Program|os suspend
2020-06-12 11:58:52.4542|INFO|Shadowsocks.Program|os wake up
2020-06-12 11:59:02.5874|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.1.9.3)
2020-06-12 11:59:02.7182|ERROR|Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error query options: 87 参数错误。
2020-06-12 11:59:08.9990|ERROR|Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error query options: 87 参数错误。

**Comment by managerstrange** [comment] 2020-06-12 04:16
Help!

**Comment by database64128** [comment] 2020-06-12 04:56
Probably some related system services are stopped after waking up from sleep? Please try out the [latest artifacts](https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/33460553/job/as5m1ss6h6dj2a8o/artifacts) from `v5/master` and attach the logs if the issue still persists.

**Comment by managerstrange** [comment] 2020-06-12 05:34
> Probably some related system services are stopped after waking up from sleep? Please try out the [latest artifacts](https://ci.appveyor.com/project/celeron533/shadowsocks-windows/builds/33460553/job/as5m1ss6h6dj2a8o/artifacts) from `v5/master` and attach the logs if the issue still persists.

It doesn't work.WinHttpAutoProxySvc is working.I have no idea what to do.
![1](https://user-images.githubusercontent.com/35600212/84468386-454bb600-acb1-11ea-9cab-b6e356c55120.png)
{
  "Calculations": {
    "AverageLatency": 0.0,
    "MinLatency": 0.0,
    "MaxLatency": 0.0,
    "AverageInboundSpeed": 0.0,
    "MinInboundSpeed": 0.0,
    "MaxInboundSpeed": 0.0,
    "AverageOutboundSpeed": 0.0,
    "MinOutboundSpeed": 0.0,
    "MaxOutboundSpeed": 0.0,
    "AverageResponse": 0.0,
    "MinResponse": 0.0,
    "MaxResponse": 0.0,
    "PackageLoss": 0.0
  },
  "StatisticsEnabled": false,
  "ByHourOfDay": true,
  "Ping": false,
  "ChoiceKeptMinutes": 10,
  "DataCollectionMinutes": 10,
  "RepeatTimesNum": 4
}

**Comment by chenshaoju** [comment] 2020-06-12 05:44
Please make sure `WinHTTP Web Proxy Auto-Discovery Service (WinHttpAutoProxySvc)` service is running:
![image](https://user-images.githubusercontent.com/515763/84469086-cfe0e500-acb2-11ea-88be-0973d0c74151.png)

**Comment by managerstrange** [comment] 2020-06-12 05:51
> Please make sure `WinHTTP Web Proxy Auto-Discovery Service (WinHttpAutoProxySvc)` service is running:
> ![image](https://user-images.githubusercontent.com/515763/84469086-cfe0e500-acb2-11ea-88be-0973d0c74151.png)

确实是在运行状态下，我按照这个做了，可惜还是提醒87参数错误https://blog.csdn.net/xkKevin/article/details/105642569

**Comment by chenshaoju** [comment] 2020-06-12 06:03
请尝试更新看看：https://github.com/shadowsocks/shadowsocks-windows/releases 。

**Comment by database64128** [comment] 2020-06-12 06:10
Check `user-wininet.json` and attach its content.

**Comment by managerstrange** [comment] 2020-06-13 02:00
> Check `user-wininet.json` and attach its content.

Here
{
  "UserSettingsRecorded": false,
  "Flags": "1",
  "ProxyServer": "",
  "BypassList": "",
  "PacUrl": ""
}

**Comment by managerstrange** [comment] 2020-06-13 02:05
> 请尝试更新看看：https://github.com/shadowsocks/shadowsocks-windows/releases 。

还是没用T^T
![2](https://user-images.githubusercontent.com/35600212/84557401-6ec21b80-ad5d-11ea-8ad3-1bd47b30c0a4.png)
![3](https://user-images.githubusercontent.com/35600212/84557404-75e92980-ad5d-11ea-9474-a9b62e03cae0.png)


![3](https://user-images.githubusercontent.com/35600212/84557402-708bdf00-ad5d-11ea-8c1a-3993c88d1e79.png)

**Comment by managerstrange** [comment] 2020-06-13 02:09
> 请尝试更新看看：https://github.com/shadowsocks/shadowsocks-windows/releases 。

还是没用T^T
![2](https://user-images.githubusercontent.com/35600212/84557457-fa3bac80-ad5d-11ea-9773-9753406301b4.png)
![3](https://user-images.githubusercontent.com/35600212/84557459-fc057000-ad5d-11ea-9ce8-1d539080819c.png)

**Comment by managerstrange** [comment] 2020-06-13 02:10
2020-06-13 09:58:33.1028|INFO|Shadowsocks.Controller.I18N|Current language is: zh-CN
2020-06-13 09:58:35.9044|INFO|Shadowsocks.Controller.Listener|Shadowsocks started (4.1.10.0)
2020-06-13 09:58:36.2394|ERROR|Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error query options: 87 参数错误。



2020-06-13 09:59:17.5632|ERROR|Shadowsocks.Controller.SystemProxy|sysproxy - SysproxyExitError:Error query options: 87 参数错误。

**Comment by studentmain** [comment] 2020-06-15 18:11
很怪，不应该是参数错误，找到`ss_win_temp/sysproxy.exe`，从命令行运行 `sysproxy.exe query`看看有没有什么结果……

另外你的系统是什么版本

**Comment by studentmain** [comment] 2020-06-15 18:18
参考文档： https://docs.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetsetoptiona#remarks

**Comment by managerstrange** [comment] 2020-06-16 11:27
> 很怪，不应该是参数错误，找到`ss_win_temp/sysproxy.exe`，从命令行运行 `sysproxy.exe query`看看有没有什么结果……
> 
> 另外你的系统是什么版本

win10家庭中文版 1903
![4](https://user-images.githubusercontent.com/35600212/84768817-6c82ea00-b007-11ea-8e28-0c10d497d51b.png)

**Comment by studentmain** [comment] 2020-06-22 16:37
我们没法复现……

试试能不能手动设置系统的代理。

**Comment by database64128** [comment] 2020-10-02 15:51
Since there's been no updates for a few months, and it's mostly likely not a bug, I'm closing the issue.

**Closed by database64128** 2020-10-02 15:51 UTC
