### ISSUE TITLE
Shadowsocks Error v3.2 @Win7

### ISSUE THREAD

**Issue by cpjp** [shadowsocks/shadowsocks-windows#669] opened 2016-08-19 02:45 UTC
升级v3.2后，出现过好几次类似的问题，如下图：
![ss_error](https://cloud.githubusercontent.com/assets/9065820/17797190/a3896f26-65f9-11e6-8cdc-33ca45babfde.JPG)

环境：Windows 7 x64
SS版本：v3.2

个人初步怀疑，可能跟日志记录有关
每次都是在点击“显示日志”之后，有几率出现这个错误
已经开启了“详细记录日志”

**Comment by chenshaoju** [comment] 2016-08-19 02:48
请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ce2451puj40kjoe9/artifacts

**Comment by wongsyrone** [comment] 2016-08-19 02:58
What is your .NET version?

**Comment by cpjp** [comment] 2016-08-19 02:58
> 请尝试该版本：
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ce2451puj40kjoe9/artifacts

这个版本更糟，所有服务器都连不上
![ss_error2](https://cloud.githubusercontent.com/assets/9065820/17797471/b05cbb20-65fb-11e6-8e13-7d402479f9d0.JPG)

已经换回正式release的v3.2，虽然偶尔有error，还凑合能用

**Comment by cpjp** [comment] 2016-08-19 03:03
> What is your .NET version?
2.0/3.0/3.5/4.0

**Comment by wongsyrone** [comment] 2016-08-19 03:06
@Noisyfox
Windows 7, Windows Server 2008 R2, Windows XP with SP3, Windows Server 2008, Windows Vista and Windows Server 2003:  The process must not already be assigned to a job; if it is, the function fails with ERROR_ACCESS_DENIED. This behavior changed starting in Windows 8 and Windows Server 2012.

**Comment by wongsyrone** [comment] 2016-08-19 03:56
Similar to #650

**Comment by wongsyrone** [comment] 2016-08-19 04:00
Please try upgrading your .NET to 4.6. I cannot reproduce this on Win10 x64

> This issue is occurring due to .NET behavior on Win7 change that is exposing a bug in how we close UI dialogs.

ref: https://blogs.msdn.microsoft.com/petersad/2009/08/14/invoke-or-begininvoke-cannot-be-called-on-a-control-until-the-window-handle-has-been-created/

**Comment by Noisyfox** [comment] 2016-08-19 04:01
@wongsyrone 
I now added some compatibility thing in manifest but I don't have a win7 env to test it.

**Comment by wongsyrone** [comment] 2016-08-19 04:04
Neither do I.

**Comment by Noisyfox** [comment] 2016-08-19 04:06
I'll setup a win7 vm tonight and test whether it works.

**Comment by Noisyfox** [comment] 2016-08-20 01:41
try this version and see whether it still have those issues.
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ro9v8mnnfdf51a92/artifacts

**Comment by 4wheels** [comment] 2016-08-22 10:41
I have the same problem. The notification is as below.
![Uploading image.png…]()

System version: Windows 10 x64
Shadowsocks version: v.3.2

**Comment by Noisyfox** [comment] 2016-08-22 10:43
@4wheels You didn't upload the image.

**Comment by 4wheels** [comment] 2016-08-22 11:32
@Noisyfox Image has uploaded.

**Comment by Noisyfox** [comment] 2016-08-22 12:33
@dongzhenye 
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/uvu9en8tpxn5c2pe/artifacts
try this version

**Comment by wongsyrone** [comment] 2016-08-23 00:23
@dongzhenye Yours is similar to #664

**Comment by wongsyrone** [comment] 2016-08-29 08:47
Test latest AppVeyor version.

**Closed by wongsyrone** 2016-08-29 08:47 UTC
